Set NoCount On	
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (1,'AL','Alabama')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (4,'AZ','Arizona')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (5,'AR','Arkansas')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (6,'CA','California',-1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (8,'CO','Colorado',1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (9,'CT','Connecticut')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (12,'FL','Florida',1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (13,'GA','Georgia')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (15,'HI','Hawaii')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (16,'ID','Idaho')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (17,'IL','Illinois',-1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (18,'IN','Indiana')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (19,'IA','Iowa')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (20,'KS','Kansas')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (21,'KY','Kentucky')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (22,'LA','Louisiana')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (23,'ME','Maine')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (24,'MD','Maryland')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (25,'MA','Massachusetts')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (26,'MI','Michigan',-1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (27,'MN','Minnesota')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (28,'MS','Mississippi')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (29,'MO','Missouri')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (30,'MT','Montana',1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (31,'NE','Nebraska')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (32,'NV','Nevada')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (33,'NH','New Hampshire')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (34,'NJ','New Jersey')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (35,'NM','New Mexico')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (36,'NY','New York',-1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (37,'NC','North Carolina',1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (39,'OH','Ohio',-1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (40,'OK','Oklahoma')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (41,'OR','Oregon',1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (42,'PA','Pennsylvania',-1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (44,'RI','Rhode Island')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (45,'SC','South Carolina')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (47,'TN','Tennessee')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (48,'TX','Texas',2)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (49,'UT','Utah')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (51,'VA','Virginia')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (53,'WA','Washington')
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name],CD_Change_2022) Values (54,'WV','West Virginia',-1)
Insert Into GerryMatter_Raw.dbo.[State] (FIPS,Postal,[Name]) Values (55,'WI','Wisconsin')